pipeline:
  lint:
    when:
      event:
      - push
    image: node:16
    commands:
    - yarn
    - yarn lint
    - yarn stylelint

  test:
    when:
      event:
      - push
    image: node:16
    commands:
    - apt update
    - apt install firefox-esr -y --no-install-recommends
    - yarn 
    - yarn unit

  build:
    when:
      event:
      - tag
    image: node:16
    commands:
    - yarn
    - yarn build

  release:
    when:
      event:
      - tag
    image: node:16
    secrets:
    - SCW_ACCESS_KEY
    - SCW_SECRET_KEY
    - SCW_DEFAULT_ORGANIZATION_ID
    commands:
      - apt-get install -y rclone wget zip
      - wget https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scaleway-cli_2.5.1_linux_amd64
      - mv scaleway-cli_2.5.1_linux_amd64 scaleway-cli
      - chmod +x scaleway-cli
      - ./scaleway-cli object config install type=rclone
      - zip akkoma-fe.zip -r dist
      - rclone copyto akkoma-fe.zip scaleway:akkoma-updates/frontend/akkoma-fe.zip
